import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { FormProvider } from "@/context/FormContext";
import { Toaster } from "@/components/ui/sonner";
import { MCQProvider } from "@/context/MCQContext";
import { FormInfoProvider } from "@/context/FormInfoContext"; // import the new context provider
import Navbar from "@/componets/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-900`}
      >
        <FormProvider>
          <MCQProvider>
            <FormInfoProvider> {/* added here */}
              <Navbar />
              <main className="pt-14 h-screen bg-gray-900 text-amber-50">
                {children}
                <Toaster />
              </main>
            </FormInfoProvider>
          </MCQProvider>
        </FormProvider>
      </body>
    </html>
  );
}
